name: Video Source Maintenance Test

on:
  push:
    paths:
      - '.github/workflows/video-source-maintenance.yml'
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello world"
